
```{r}
library(tidyverse)
library(rsample)
library(mirt)
mirtCluster()
library(here)

R.utils::sourceDirectory(here("R"))

path <- "~/Google_Drive/6_Dissertation/sim.cv.irt/"
source(paste0(path, "R/elpl_helpers.R"))
source(paste0(path, "R/elpl_out.R"))

set.seed(1)
```

make function

```{r}
f <- function(the_disc_ln_sd){
	set.seed(sample(1:1000000, 1))
	
	simmed <- 
		sim(
			n_items = 10, 
			disc_ln_sd = the_disc_ln_sd, 
			n_ref = 100, 
			n_foc = 100, 
			mean_foc = 0
		)

	models <- 
		tibble(type = c("Rasch", "2PL", "3PL")) %>% 
		mutate(
			# model
			
			model = type %>% map(~ mirt(simmed$data, 1, .)),
			
			fscore = model %>% map(fscores),
			
			p = map2(model, fscore, get_p),
			
			# practical outcomes
			
			theta_rmse = 
				fscore %>% 
				map_dbl(~ rmse(., simmed$students$theta)),
			
			theta_rankcorr =
				fscore %>% 
				map_dbl(
					~ cor(., simmed$students$theta, method = "spearman")
				),
			
			accuracy = p %>% map_dbl(~ mean((. > 0.5) == simmed$data)),
			
			bott20 = 
				map_dbl(
					fscore, 
					~ fscore_to_perc_of_bott20_identified(., simmed)
				),
			
			# theoretical outcome
			
			elpl_marg = 
				model %>% 
				map_dbl(
					~ elpl_y_outin(
						data = simmed$data,
						pars = simmed$items,
						model = .,
						theta_mu = 0,
						theta_var = 1
					)
				),
			
			# practical model comparison
			
			log_lik = model %>% map_dbl(~ .@Fit$logLik),
	        anova_p = map2_dbl(model, lag(model), get_p_from_anova),
	        aic = model %>% map_dbl(~ .@Fit$AIC),
	        aic_c = model %>% map_dbl(~ .@Fit$AICc),
	        bic = model %>% map_dbl(~ .@Fit$BIC),
	        dic = model %>% map_dbl(~ .@Fit$DIC)
		)
	
	models
}
```

execute function

```{r}
out <- 
	crossing(run = 1:5, disc_ln_sd = seq(0, 0.5, 0.25)) %>% 
	mutate(models = disc_ln_sd %>% map(f))
```

